site_name: ITMO-ICT-WebDevelopment

theme:
  name: readthedocs
  
nav:
 - Начальная страница: index.md
 - Лабораторная работа №1: lr1.md
 - Лабораторная работа №2: lr2.md
 - Практическая работа 3.1: prac2.md
 - Лабораторная работа 3: lr3.md
markdown_extensions:
    - toc:
        permalink: True