site_name: Kozlov Ivan - WEB - ICT
nav:
    - Главная страница: index.md
    - Лабораторные:
        - Лабораторная №1: lr_1.md
        - Лабораторная №2: lr_2.md

theme:
  name: null
  custom_dir: "MkDocs-Theme-Cinder-Superhero/cinder-superhero"

markdown:
  extra: true