site_name: Web Labs Docs

theme:
  name: "material"

nav:
  - index.md
  - report_lab1.md
  - report_lab2.md
  - report_pr3.md
  - report_lab3.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences